# This workflow will build Python packages on every commit.

name: Build runixinstall

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-uv python-setuptools python-pip
          pacman --noconfirm -Sy python-pyparted python-pydantic
      - name: Remove existing runixinstall (if any)
        run: 
          uv pip uninstall runixinstall --break-system-packages --system
      - name: Build runixinstall
        run: uv build --no-build-isolation --wheel
      - name: Install runixinstall
        run: |
          uv pip install dist/*.whl --break-system-packages --system --no-build --no-deps
      - name: Run runixinstall
        run: |
          python -V
          runixinstall --script guided -v
          runixinstall --script only_hd -v
          runixinstall --script minimal -v
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: runixinstall
          path: dist/*
