#on:
#    push:
#        paths:
#        - 'runixinstall/locales/**'
#    pull_request:
#        paths:
#        - 'runixinstall/locales/**'
#name: Verify local_generate script was run on translation changes
#jobs:
#    translation-check:
#        runs-on: ubuntu-latest
#        container:
#            image: archlinux/archlinux:latest
#        steps:
#            - uses: actions/checkout@v4
#            - run: pacman --noconfirm -Syu python git diffutils
#            - name: Verify all translation scripts are up to date
#              run: |
#                cd ..
#                cp -r runixinstall runixinstall_orig
#                cd runixinstall/runixinstall/locales
#                bash locales_generator.sh 1> /dev/null
#                cd ../../..
#                git diff \
#                  --quiet --no-index --name-only \
#                  runixinstall_orig/runixinstall/locales \
#                  runixinstall/runixinstall/locales \
#                  || (echo "Translation files have not been updated after translation, please run ./locales_generator.sh once more and commit" && exit 1)
